// Generated by scripts/blender/bake-room-visibility.py; do not hand-edit.
export const ROOM_VISIBILITY_ARTIFACT = {
  "source": "1872c192b090f95352850d63e762e5a0378c4742",
  "sourceHashes": {
    "src/build/orange-house.ts": "e7d2b4e2c89530958bf4f97ba0c07bc65d6eb8c60775119874ac5519608d3b56",
    "src/build/interior-furniture.ts": "5e269c9cafe3b948431a00277c2cb47d37db12b0796acd59de4d51fdcc1a3b15",
    "src/core/layout.ts": "15f6bff8aa7cb61cdd8e6fa1b4b08a7c23d2c6aafed6fef11fe6f801d662b05d",
    "src/core/static-batch.ts": "480e72af29863f05a0653ccd0eae5e1026d1be4f228245c5c52776ed634af0d6"
  },
  "bounds": {
    "min": [
      -1,
      0,
      -21.3
    ],
    "max": [
      6.4,
      6.25,
      -16
    ]
  },
  "dimensions": [
    32,
    28,
    24
  ],
  "directions": 64,
  "meshes": 58,
  "occluderSha256": "830018f593a454940dab8e3fb90fb21fdf42f878d210554250fe8640f6bbe0ec",
  "triangles": 18132,
  "sourceIsBaseRevision": true,
  "authoringSourceHashes": {
    "scripts/blender/bake-room-visibility.py": "1486c6ef4cf8a19e13dd8292b80ff48ec6f854656ec0a1ee2ea46fd78ce812ea",
    "scripts/blender/export-room-occluders.mjs": "343ee9ce812937d8e63edc1fc5f14f5e88645a33b39c4c7be5f01fbe415a1509"
  },
  "seconds": 6.2788380999991205,
  "blender": "5.1.2",
  "route": "guarded CPU Blender BVH; no GPU/no rendering",
  "algorithm": "original cosine-lobe visibility with bounded distance-fill approximation; not GI",
  "files": {
    "positive.bin": {
      "bytes": 86016,
      "sha256": "7a86ce99991a1e211201c6ba4dfd6239f6714b4092594cca0a4d6944346d4b4d"
    },
    "negative.bin": {
      "bytes": 86016,
      "sha256": "44a2811d47659f98367a5fbc74c4e89405202604b899ef27b3984c8078bee9a7"
    }
  },
  "license": "original project data; no external model or asset inputs"
} as const;
