/**
 * Traversability probe.
 *
 * A map that photographs well and cannot be walked is not a map. This drives the real
 * player controller (not a raycast approximation) along a set of routes a player must
 * be able to take, and reports where it gets stuck.
 *
 *   node scripts/traverse.mjs
 */
import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import net from 'node:net';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

function freePort() {
  return new Promise((res, rej) => {
    const s = net.createServer();
    s.listen(0, '127.0.0.1', () => {
      const p = s.address().port;
      s.close(() => res(p));
    });
    s.on('error', rej);
  });
}

// 60 s was not enough with sibling build lanes saturating the CPU: the harness
// reported 'server never came up' for a server that was merely slow to start,
// which reads as a map failure rather than a busy machine.
async function waitForServer(url, ms = 240000) {
  const t0 = Date.now();
  while (Date.now() - t0 < ms) {
    try { if ((await fetch(url)).ok) return true; } catch { /* not up */ }
    await new Promise((r) => setTimeout(r, 250));
  }
  return false;
}

const port = await freePort();
// windowsHide: node defaults it to FALSE, and with shell:true on Windows every
// one of these spawns a visible cmd.exe window. Running captures in a loop put
// console windows over the owner's screen and stole his keyboard focus.
const server = spawn(
  process.platform === 'win32' ? 'npx.cmd' : 'npx',
  ['vite', 'preview', '--port', String(port), '--strictPort'],
  { cwd: ROOT, stdio: 'ignore', shell: process.platform === 'win32', windowsHide: true },
);
const url = 'http://localhost:' + port + '/';
if (!await waitForServer(url)) {
  console.error('[traverse] server never came up');
  server.kill();
  process.exit(1);
}

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 800, height: 600 } });
await page.goto(url, { waitUntil: 'load', timeout: 90000 });
await page.waitForFunction(() => window.__NT && window.__NT.ready === true, null, { timeout: 180000 });
await page.waitForTimeout(600);

/**
 * Routes a player must be able to walk. Waypoints are world x/z and must stay OUT of
 * the house footprints - going around is the player's normal path; going through needs
 * a door, which the door scan below locates rather than assumes.
 */
const ROUTES = [
  // GENERATED by `node scripts/paths.mjs`, which floods the collision world from spawn
  // A with the player's radius eroded out and prints a real path to each landmark.
  // Re-run it and re-paste after any geometry change; do not hand-edit a waypoint.
  //
  // Why: a straight line between two sensible-looking points crosses yard cover, and
  // this harness then says "FAIL" in exactly the words it uses for a sealed map. Hours
  // went into that confusion. paths.mjs answers "is it reachable at all"; this file
  // answers "is the lane a player would actually run still clear".
  //
  // NOTE the west flank route: it goes out to the street and back, because the squeeze
  // past the orange carport is currently sealed for walking. That is a real defect, and
  // the path length (41 m for what should be ~14 m) is what exposes it.
  { name: 'spawnA -> spawnB',
    pts: [[-4, -34.2], [-2.2, -25.6], [0.4, -17.4], [1.4, -8.8], [6.4, -0.2], [3, 8.2],
          [-0.8, 16], [0.2, 24.6], [1.4, 33.2], [1.2, 34.2]] },
  { name: 'spawnA -> the turning circle',
    pts: [[-4, -34.2], [-3.4, -29.2], [-2.2, -24.2], [-0.2, -19.6], [0, -15.4],
          [-4.8, -10.8], [-6.8, -5.8], [-5.2, -0.8], [0, 0]] },
  { name: 'spawnA -> the east flank, round the orange house',
    pts: [[-4, -34.2], [-4, -30.6], [-2.4, -27], [-2.2, -23.4], [-0.2, -20.2],
          [1.2, -16.6], [4.6, -15.2], [8.2, -16], [11.8, -19.6], [12.2, -20]] },
  { name: 'spawnA -> the west road stem',
    pts: [[-4, -34.2], [-3.8, -29.6], [-2.2, -25], [-0.4, -20.8], [1.4, -16.2],
          [-3, -12.8], [-7, -8.2], [-11.6, -5.8], [-16.2, -1.2], [-17.4, 0]] },
  { name: 'spawnA -> the enemy back door',
    pts: [[-4, -34.2], [-2.2, -26.4], [-0.2, -19], [1.4, -11.2], [5.6, -3.4], [6.4, 4.4],
          [0.6, 11.2], [-0.8, 19], [1.4, 26.8], [1.6, 28]] },
];

const results = await page.evaluate(async (routes) => {
  const nt = window.__NT;
  const out = [];
  for (const route of routes) {
    nt.probeReset(route.pts[0][0], route.pts[0][1]);
    let stuck = null;
    let reached = 0;
    for (let i = 1; i < route.pts.length; i++) {
      const [tx, tz] = route.pts[i];
      if (!nt.probeWalkTo(tx, tz, 1400)) {
        stuck = { target: [tx, tz], at: nt.probePos() };
        break;
      }
      reached = i;
    }
    out.push({ name: route.name, reached, legs: route.pts.length - 1, stuck });
  }
  return out;
}, ROUTES);

/**
 * Door scan. Walk at the wall from 2 m out, at 0.5 m intervals along it, and record
 * every x that gets through. This finds the doors instead of assuming where they are,
 * and it fails loudly if a house has no way in at all.
 */
const doors = await page.evaluate(() => {
  const nt = window.__NT;
  const FRONT = 15.4;   // FRONT_LAWN_OUTER
  const BACK = 26.6;    // HOUSE_BACK
  const scan = (side, wallZ, fromOutside) => {
    const open = [];
    for (let x = -6.2; x <= 6.2; x += 0.4) {
      const startZ = side * (wallZ + (fromOutside ? 2.4 : -2.4));
      const endZ = side * (wallZ - (fromOutside ? 2.6 : -2.6));
      nt.probeReset(x, startZ);
      if (nt.probeWalkTo(x, endZ, 420)) open.push(+x.toFixed(1));
    }
    // collapse consecutive hits into spans
    const spans = [];
    for (const v of open) {
      const last = spans[spans.length - 1];
      if (last && Math.abs(v - last[1]) < 0.75) last[1] = v;
      else spans.push([v, v]);
    }
    return spans;
  };
  return {
    orangeStreet: scan(-1, FRONT, true),
    orangeYard: scan(-1, BACK, false),
    whiteStreet: scan(1, FRONT, true),
    whiteYard: scan(1, BACK, false),
  };
});

/**
 * Verge scan. A continuous hedge along a front lawn would wall a team into its own
 * half without any single collider looking wrong. Walk lawn -> street at intervals
 * and report where the boundary is actually permeable.
 */
const verge = await page.evaluate(() => {
  const nt = window.__NT;
  const scan = (side) => {
    const open = [];
    for (let x = -13; x <= 13; x += 0.5) {
      nt.probeReset(x, side * 12.5);
      if (nt.probeWalkTo(x, side * 5.5, 420)) open.push(+x.toFixed(1));
    }
    const spans = [];
    for (const v of open) {
      const last = spans[spans.length - 1];
      if (last && Math.abs(v - last[1]) < 0.75) last[1] = v;
      else spans.push([v, v]);
    }
    return spans;
  };
  return { orangeVerge: scan(-1), whiteVerge: scan(1) };
});

// the one invariant, read from the running scene rather than re-derived here
const hand = await page.evaluate(() => window.__NT.stats().handedness);

await browser.close();
server.kill();

let bad = 0;
console.log('[traverse] routes:');
for (const r of results) {
  const ok = r.stuck === null;
  if (!ok) bad++;
  console.log('  ' + (ok ? 'PASS' : 'FAIL') + '  ' + r.name
    + '  (' + r.reached + '/' + r.legs + ' legs)'
    + (r.stuck ? '  stuck heading to ' + JSON.stringify(r.stuck.target)
        + ' at ' + JSON.stringify(r.stuck.at.map((n) => +n.toFixed(1))) : ''));
}

console.log('\n[traverse] door scan - x spans where the player got through the wall:');
let faceless = 0;
for (const [k, spans] of Object.entries(doors)) {
  if (!spans.length) faceless++;
  const txt = spans.length
    ? spans.map((v) => (v[0] === v[1] ? String(v[0]) : v[0] + '..' + v[1])).join(',  ')
    : 'NONE - no way through this face';
  console.log('  ' + k.padEnd(14) + txt);
}

const handOk = Array.isArray(hand) && hand.every(Boolean);
console.log('\n[traverse] invariant - garage on the RIGHT from both back yards: '
  + (handOk ? 'PASS' : 'FAIL ' + JSON.stringify(hand)));

console.log('\n[traverse] verge scan - x spans where lawn -> street is passable:');
let walled = 0;
for (const [k, spans] of Object.entries(verge)) {
  const total = spans.reduce((a, v) => a + (v[1] - v[0]) + 0.5, 0);
  if (total < 8) walled++;
  console.log('  ' + k.padEnd(14) + (spans.length
    ? spans.map((v) => v[0] + '..' + v[1]).join(',  ') + '   (' + total.toFixed(1) + ' m open)'
    : 'NONE - this team is walled into its own half'));
}

console.log('\n[traverse] ' + (results.length - bad) + '/' + results.length
  + ' routes passed;  ' + (4 - faceless) + '/4 house faces enterable');
process.exit(bad || faceless || walled || !handOk ? 1 : 0);
